### ISSUE TITLE
IE only - searchbox onChange event issues

### ISSUE THREAD

**Issue by SaraBurp** [StanPri/EmployeeDirectoryApp#31]
* Paste from mouseclick does not trigger an onChange event
* IE "helps" by adding an "x" to a text box
  * Clicking the "x" clears the field, but does not trigger an onChange event

* If either of the above issues are encountered...
  * Clicking the "Search" button does nothing (*this is __expected__ behavior*)
  * Pressing the "Enter" key DOES trigger an onChange event (*this is __unexpected__ behavior*)

**Comment by cwkummer** [comment]
Changed to onInput vs onChange to support Internet Exploder. Used CSS to remove "x".
